#!/usr/bin/env node
/**
 * Regenerate `server/config.example.json` from `DEFAULT_CONFIG`.
 *
 * The example file must never be hand-edited (it drifts from the real
 * defaults), but it also should not leak machine-specific paths or runtime
 * state — this script derives it from the live defaults and then:
 *   * rewrites absolute paths under `server/` back to `./…`,
 *   * replaces secrets/ids with placeholders,
 *   * drops runtime bookkeeping (onboarding progress, TOTP material).
 *
 *   node scripts/config-example.js          (or: npm run config:example)
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const SERVER_DIR = path.join(__dirname, '..', 'server');
const OUT = path.join(SERVER_DIR, 'config.example.json');

const { DEFAULT_CONFIG } = require(path.join(SERVER_DIR, 'config.js'));

/** Absolute paths back to portable, repo-relative ones. */
function portable(value) {
  if (typeof value !== 'string' || !path.isAbsolute(value)) return value;
  const rel = path.relative(SERVER_DIR, value);
  return rel.startsWith('..') ? value : `./${rel.split(path.sep).join('/')}`;
}

function walk(node) {
  if (Array.isArray(node)) return node.map(walk);
  if (!node || typeof node !== 'object') return portable(node);
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    // Runtime bookkeeping and generated secrets never belong in the example.
    if (key === 'completedAt' || key === 'secret' || key === 'recoveryHashes') continue;
    out[key] = walk(value);
  }
  return out;
}

const example = walk(JSON.parse(JSON.stringify(DEFAULT_CONFIG)));

// ---- placeholders ---------------------------------------------------------
example.server.host = example.server.host || '0.0.0.0';
example.auth.username = 'admin';
example.auth.passwordHash = 'will be generated by npm run setup';
example.auth.jwtSecret = 'CHANGE_THIS_TO_A_RANDOM_64_CHAR_STRING';
example.auth.subsonic = { enabled: false, username: 'admin', passwordEnc: '' };
example.media.paths = Object.fromEntries(
  Object.entries(example.media.paths || {}).map(([name]) => [name, `./media/${name}`]),
);

fs.writeFileSync(OUT, `${JSON.stringify(example, null, 2)}\n`);
console.log(`[config-example] wrote ${path.relative(process.cwd(), OUT)} (${Object.keys(example).length} top-level keys)`);
